### ISSUE TITLE
Keine Verschleierung im Xform(?)

### ISSUE THREAD

**Issue by mhekeler** [RexDude/email_obfuscator#11]
Hallo,

wenn ich in einem mit XForm Addon erstellten Kontaktformular ein Auswahlfeld habe, werden diese Adressen nicht verschleiert.
also ich habe im select dann die values xy@tld.de, z@tld.de. Hier macht das email_obfuscator addon garnichts. Ist das so richtig?
Sollte ich im Kontaktformular nur xys und z schreiben und dann im Emailtemplate das @tld.de anhängen? Geht das?

**Comment by RexDude** [comment]
Email-Adressen innerhalb von Tags werden nicht verschleiert. Das kommt sonst nämlich nicht so gut wenn da script Tags plötzlich drin stehen.  Du solltest gar keine Email-Adressen in dem Select Feld drin stehen haben sonder stattdessen serverseitig nach dem submitten der Form drauf reagieren und demenstprechend dein Aktion machen.

**Comment by mhekeler** [comment]
Das mit den Script Tags leuchtet mt ein.
Aber deinen Tipp mit dem serverseitigen Reagieren hab ich noch nicht ganz verstanden. Kannst du mir das noch genauer erklären, bitte?

BTW 
Ich hab grad  versucht, über das von dir angesprochene Verfahren was zu lesen, aber ich habe nur im Wiki was gefunden wo dann aber die Emailadressen in dem Modul stehen (meintest du es so?)
http://www.redaxo.org/de/wiki/index.php?n=R4.XForm-FormularAddOn
    ein select-Feld einfügen (select|receiver|Empfänger|Allgemein=info;Vetrieb=vertrieb)
    ein action|email Feld eintragen mit folgendem Wert für die Empfängeradresse: ###receiver###@meinedomain.tld

**Comment by RexDude** [comment]
Ich bau deshalb XForm Forumlare immer mit PHP (kann man googlen). So kann ich seber genau steuer was dann letzendlich passiert. Alles weitere bitte ins REDAXO Forum posten. Der Issue Tracker ist nur für Bugreports oder Featurewünsche gedacht ;)

**Comment by mhekeler** [comment]
Danke :-)
