### ISSUE TITLE
Fehler bei Verlinkung mit Bild

### ISSUE THREAD

**Issue by Sysix-Coding** [RexDude/email_obfuscator#8]
Hey hey,

ich hab gerade ein Problem festgestellt.
Ich hab in mein Template direkt die E-Mail Adresse eingeben und dazu ein kleines img Verlinkt:
```
<a href="mailto:info@domain.de" title="Send Mail" id="sendmail"><img src="Bilder/mailbutton.png" alt="sendmail" /></a>
```

Wenn ich die CSS Methode nur aktiviere kommt das raus:
```
<span class="hide">vasbp</span>info<span class="hide">pbsav</span>[at]<span class="hide">vasbp</span>domain.de
```
Problem:
- Bild verschwindet
- Verlinkung verschwindet

Wenn ich die JS Methode nur aktiviere kommt das raus:
```
<script type="text/javascript">/* <![CDATA[ */document.write("<n uers=\"znvygb:vasb@pap-ubsznaa.qr\"><vzt fep="Ovyqre/znvyohggba.cat" nyg="fraqznvy" /></n>".replace(/[a-zA-Z]/g, function(c){return String.fromCharCode((c<="Z"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);}));/* ]]> */</script><noscript><em>&gt;&gt;&gt; Bitte JavaScript aktivieren um die Email-Adresse sichtbar zu machen! / Please activate JavaScript to see email address! &lt;&lt;&lt;</em></noscript>
```
Problem:
- Kein Ausgabe Text für den Besucher

Wenn ich beide Methoden aktiviere, kannst du dir ja denken was rauskommt ;) Da die CSS Methode einfach nur in NoScript eingefügt wird.

Kannst du bitte mal nachschauen und nen Fix raushauen ;)?

Gruß Sysix

**Comment by RexDude** [comment]
Lösung: Bild per CSS reinmachen :D
